### ISSUE TITLE
Login panics on Ctrl+C and Ctrl+D

### ISSUE THREAD

**Issue by xTibor** [redox-os/userutils#5]
Pressing Ctrl+C or Ctrl+D at the Redox login prompt results in a panic. It was a bit hard to notice because the error messages are cleared immediately and the login process is restarted by the `getty` daemon.

**Panic messages:**
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Custom { kind: Interrupted, error: StringError("ctrl+c") }) }', /home/user/git/redox/rust/src/libcore/result.rs:860

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Custom { kind: UnexpectedEof, error: StringError("ctrl+d") }) }', /home/user/git/redox/rust/src/libcore/result.rs:860
```

**Comment by xTibor** [comment]
It has been fixed, it doesn't panic anymore.
